import "../../../app/globals.css";
import type { Metadata } from "next";
import Header from "../../components/Header";
import FooterComponent from "../../components/FooterComponent";

export const metadata: Metadata = {
  title: "Rafael and Rafhael's Tech Blog",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <Header title="NameLess" subTitle="" />
      {children}
    </div>
  );
}
