import type { Metadata } from "next";
import Header from "./components/Header";
import Footer from "./components/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Rafael and Rafhael's Tech Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`max-w-3xl mx-auto md:px-10 px-4`}>
        <Header
          title="Rafael and Rafhael's Tech Blog"
          subTitle="Bem-Vindo ao nosso Tech Blog 👨‍💻"
        />
        {children}
        <Footer />
      </body>
    </html>
  );
}
