import "./globals.css";
import type { Metadata } from "next";
import Header from "./components/Header";
import FooterComponent from "./components/FooterComponent";

export const metadata: Metadata = {
  title: "Rafael and Rafhael's Tech Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className={`max-w-4xl mx-auto md:px-10 px-4 relative`}>
          <Header title="NameLess" subTitle="" />

          {children}
          <FooterComponent />
        </div>
      </body>
    </html>
  );
}
